
version: 2

sources:
    - name: staging
      #For bigquery:
      #database: taxi-rides-ny-339813

      # For postgres:
      database: serious-sylph-377018

      schema: dezoomcamp

      # loaded_at_field: record_loaded_at
      tables:
        - name: green
        - name: yellow
         # freshness:
           # error_after: {count: 6, period: hour}



      